docs(rejson): python rootPath() -> root_path()
In python, the docs tutorial(https://developer.redis.com/howtos/redisjson/using-python/) does not work for the hello world for rejson.

It appears to want `root_path()` instead of `rootPath()`

```python
python
Python 3.8.10 (default, Nov 26 2021, 20:14:08) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import redis
>>> from redis.commands.json.path import Path
>>> client = redis.Redis(host='localhost', port=6379, db=0)
>>> jane = {
...      'name': "Jane", 
...      'Age': 33, 
...      'Location': "Chawton"
...    }
>>> 
>>> client.json().set('person:1', Path.rootPath(), jane)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'Path' has no attribute 'rootPath'
>>> dir(Path)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', 'root_path', 'strPath']
>>> client.json().set('person:1', Path.root_path(), jane)
True
```